import webbrowser
import time

webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)
webbrowser.open('video link')
time.sleep(2)



