import requests
import time

print("Sending Views")

requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)
requests.get('video link')
time.sleep(1)

